export const FETCH_LOGS_SUCCESS = 'FETCH_LOGS_SUCCESS';
export const FETCH_LOG_SUCCESS = 'FETCH_LOG_SUCCESS';
export const REQUEST_LOG = 'REQUEST_LOG';
export const SET_AUTH_USER = 'SET_AUTH_USER';
export const RESET_AUTH_STATE = 'RESET_AUTH_STATE';
export const FETCH_USER_LOGS_SUCCESS = 'FETCH_USER_LOGS_SUCCESS';
